states:
  Lethal: 0
  Danger: 1
  Warning: 2
  Safe: 3
  Unknown: 10

transitions:
  Lethal:
    Unknown: stop_action
    Lethal: idle
    Danger: stop_action!
    Warning: slow_action!
    Safe: human_intervention
  Danger:
    Unknown: stop_action
    Lethal: stop_action
    Danger: idle
    Warning: stop_action!
    Safe: human_intervention
  Warning:
    Unknown: slow_action
    Lethal: slow_action
    Danger: stop_action
    Warning: idle
    Safe: slow_action!
  Safe:
    Unknown: slow_action
    Lethal: human_intervention
    Danger: human_intervention
    Warning: slow_action
    Safe: idle
  Unknown:
    Unknown: idle
    Lethal: human_intervention
    Danger: stop_action
    Warning: stop_action!
    Safe: stop_action!
