motion:
  min_value: 0
  max_value: 0
  increment: 0
  default_value: 0
linearvel:
  min_value: 0.25
  max_value: 1.5
  increment: 0.025
  default_value: 0.75
start_offset_x:
  min_value: 0.0
  max_value: -6.0
  increment: 0.1
  default_value: -3.0
start_offset_y:
  min_value: -1.0
  max_value: 10.0
  increment: 0.5
  default_value: 4.0
distanceToMove:
  min_value: 2.0
  max_value: 10.0
  increment: 0.5
  default_value: 4.0
start_yaw:
  min_value: -3.1415
  max_value: 0.0
  increment: 0.3926875
  default_value: 0
collision_distance:
  min_value: 1.2
  max_value: 1.2
  increment: 0.0
  default_value: 1.0
