safety_threshold: 0.8
resolution: 0.1
mapsize: 15
timeout: 1.0
trackingtime: 3
nprimitives: 5
proxemicradius: 0.2
detection_topics:
    #- /found_object
    #- /pointcloud_processing_node/detected_objects
    - /pointcloud_lidar_processing/found_object 
    #- /pointcloud_lidar_processing/detected_objects
    #- /pointcloud_nodelet/found_object
    #- /fusion_manager/detected_objects
pathtopic: /move_base_flex/mpc/local_plan
