#warn
0.3: [[5.0, -5.0],
    [5.0, 5.0],
    [-5.0, 5.0],
    [-5.0, -5.0]]
#danger
0.5: [[0, -4.0],
    [4.0, -3.0],
    [4.0, 3.0],
    [0, 4.0],
    [-3.0, 3.0],
    [-3.0, -3.0]]
#lethal
1.0: [[2.0, 1.0],
    [2.0, -1.0],
    [-2.0, -1.0],
    [-2.0, 1.0]]
