#warn
0.3: [[8.0, -8.0],
    [8, 8.0],
    [-8.0, 8.0],
    [-8.0, -8.0]]
#danger
0.5: [[0, -5.0],
    [5.0, -3.0],
    [5.0, 3.0],
    [0, 5.0],
    [-5.0, 3.0],
    [-5.0, -3.0]]
#lethal
1.0: [[3.0, 1.0],
    [3.0, -1.0],
    [-3.0, -1.0],
    [-3.0, 1.0]]
