grid_map_topic: /gr_safety_gridmap/grid_map
grid_map_visualizations:
  #- name: elevation_points
  #  type: point_cloud
  #  params:
  #   layer: normal_y
  - name: normal_grid
    type: occupancy_grid
    params:
     layer: normal_x
     data_min: 0.0
     data_max: 2.0