resolution: 0.25
mapsize: 10
detection_topics:
    - /detected_objects
    - /pointcloud_processing_node/detected_objects
    - /pointcloud_lidar_processing/detected_objects
pathtopic: move_base/NavfnROS/plan
