resolution: 0.5
mapsize: 20
detection_topics:
    - /detected_objects
    - /pointcloud_processing_node/detected_objects
    - /pointcloud_lidar_processing/detected_objects
pathtopic: move_base/NavfnROS/plan
