safety_threshold: 500.0
resolution: 0.25
mapsize: 15
timeout: 1.00
trackingtime: 3
nprimitives: 9
proxemicradius: 0.05
detection_topics:
    #- /detected_objects
    #- /pointcloud_processing_node/detected_objects
    - /pointcloud_lidar_processing/found_object 
    #- /pointcloud_lidar_processing/detected_objects
    #- /pointcloud_nodelet/found_object
    #- /fusion_manager/detected_objects
pathtopic: move_base/NavfnROS/plan
