resolution: 0.5
mapsize: 20
timeout: 0.5
trackingtime: 5
nprimitives: 2
proxemicradius: 0.50
detection_topics:
    #- /detected_objects
    #- /pointcloud_processing_node/detected_objects
    - /pointcloud_lidar_processing/found_object 
    #- /pointcloud_lidar_processing/detected_objects
    #- /pointcloud_nodelet/found_object
    #- /fusion_manager/detected_objects
pathtopic: move_base/NavfnROS/plan
