safety_threshold: 0.5
resolution: 0.1
mapsize: 15
timeout: 1.00
trackingtime: 3
nprimitives: 1
proxemicradius: 1.0
detection_topics:
    #- /detected_objects
    #- /pointcloud_processing_node/detected_objects
    - /pointcloud_lidar_processing/found_object 
    #- /pointcloud_lidar_processing/detected_objects
    #- /pointcloud_nodelet/found_object
    #- /fusion_manager/detected_objects
pathtopic: move_base/NavfnROS/plan
