#lethal
3: [[2.0, 2.0],
         [-2.0, 2.0],
         [-2.0, -2.0],
         [2.0, -2.0]]
#danger
2: [[2.0, 2.0],
    [2.0, -2.0],
    [4.0, -2.0],
    [4.0, 2.0]]

2: [[-2.0, -2.0],
    [-2.0, -6.0],
    [0, -6.0],
    [0, -2.0]]
