#danger
3: [[4.0, 5.0],
    [4.0, -5.0],
    [-4.0, -5.0],
    [-4.0, 5.0]]
3: [[-1.0, 1.0],
    [-1.0, -1.0],
    [-2, -1.0],
    [-2, 1.0]]
#warn
1: [[4.0, -5.0],
    [4.0, 5.0],
    [8.0, 8.0],
    [8.0, -8.0]]

#lethal
4: [[1.0, 1.0],
    [1.0, -1.0],
    [-1.0, -1.0],
    [-1.0, 1.0]]
