#warn
0.25: [[2.5, -7.0],
    [2.5, 7.0],
    [5.0, 8.0],
    [5.0, -8.0]]
#danger
0.75: [[2.5, 7.0],
    [2.5, -7.0],
    [-5.0, -5.0],
    [-5.0, 5.0]]
#lethal
1: [[1.5, 2.0],
    [1.5, -2.0],
    [-2.5, -2.0],
    [-2.5, 2.0]]
