#warn
2: [[2.5, -7.0],
    [2.5, 7.0],
    [5.0, 8.0],
    [5.0, -8.0]]
#danger
4: [[2.5, 7.0],
    [2.5, -7.0],
    [-5.0, -5.0],
    [-5.0, 5.0]]
#lethal
5: [[1.5, 2.0],
    [1.5, -2.0],
    [-2.5, -2.0],
    [-2.5, 2.0]]
