#warn
1: [[8.0, -8.0],
    [8, 8.0],
    [-8.0, 8.0],
    [-8.0, -8.0]]
#danger
2: [[0, -5.0],
    [5.0, -3.0],
    [5.0, 3.0],
    [0, 5.0],
    [-5.0, 3.0],
    [-5.0, -3.0]]
#lethal
3: [[3.0, 2.0],
    [3.0, -2.0],
    [-3.0, -2.0],
    [-3.0, 2.0]]
