#danger
4: [[5.0, 5.0],
    [5.0, -5.0],
    [-5.0, -5.0],
    [-5.0, 5.0]]
4: [[-2.0, 3.0],
    [-2.0, -3.0],
    [-6, -3.0],
   [-6, 3.0]]
#warn
1: [[5.0, -6.0],
    [5.0, 6.0],
    [8.0, 8.0],
    [8.0, -8.0]]

#lethal
6: [[3.0, 3.0],
    [3.0, -3.0],
    [-2.0, -1.5],
    [-2.0, 1.5]]
