#warn
0.25: [[2.5, -5.0],
    [2.5, 5.0],
    [5.0, 3.0],
    [5.0, -3.0]]
#danger
0.75: [[2.5, 5.0],
    [2.5, -5.0],
    [-5.0, -3.5],
    [-5.0, 3.5]]
#lethal
1.0: [[1.5, 2.0],
    [1.5, -2.0],
    [-2.5, -2.0],
    [-2.5, 2.0]]
