uint16 row_id
visualization_msgs/MarkerArray plan
uint8 mode
uint8 span
string start_node
string goal_node
string task_id
---
float64 next_offset
bool suceeded
std_msgs/String safety_msg
---
#feedback
std_msgs/String reached_node
std_msgs/String completed_edge
std_msgs/String safety_msgs
float64 executing_time
bool suceeded
bool intervetion
