std_msgs/String start_node
uint16 row_id
visualization_msgs/MarkerArray plan
uint8 VISIT_ALL=0
uint8 VISIT_SOME=1
uint8 JUST_END=2
uint8 mode
uint8 span
---
float64 next_offset
bool suceeded
---
#feedback
std_msgs/String reached_node
std_msgs/String completed_edge
float64 executing_time
bool suceeded
