string object_id
string motion_type
bool setstart
bool is_motion
bool is_infinite_motion
float64 linearspeed
float64 linearspeedy
geometry_msgs/PoseStamped startpose
geometry_msgs/PoseStamped goalPose
---
bool succeeded
float64 executing_time
---
bool backward
bool is_alive
